# Site settings
title: Retro Report
email: budparr@sonnetmedia.net
tagline: "Headlines Fade. The Stories Continue"
description: "An innovative documentary news organization launched in 2013 as a timely online counterweight to today’s 24/7 news cycle"
description_long: "How often does a great story dominate the headlines, only to be dropped from the news cycle? How often do journalists tell us of a looming danger or important discovery – only to move quickly to the next new thing? What really happened? How did these events change us? And what are the lingering consequences that may affect our society to this day?
<br /><br />
These are the questions we are answering at Retro Report, an innovative documentary news organization launched in 2013 as a timely online counterweight to today’s 24/7 news cycle."
url: http://www.retroreport.org/
email_signup_heading: Get RETRO REPORT by Email

#CONTENT VARIABLES

video_providers:
  - youtube
  - vimeo
  - direct-link

appearances:
  - light-text
  - dark-text

backstory_types:
  - backstory
  - 'related coverage'

roles:
  - Staff
  - Producer
  - Executive

report_types:
  - "Photo Essay"
  - "Photo Gallery"
  - "Video Extra"
  - "Multimedia Report"

page_category:
  - ''
  - about

# == DO NOT EDIT BELOW THIS LINE #


# BUILD VARIABLES
google_analytics_id: UA-xxxxxxx-4
bust_css_cache: true
image_url: https://retroreport.imgix.net
imgix:
  source: retroreport.imgix.net
production: false
full_rebuild: true
timezone: Etc/Zulu
permalink: pretty
future: false
version: 3.0.3

#source:       .
#destination:  ./_site
#plugins_dir:  ./_plugins
layouts_dir:  ./_app/_layouts
#data_dir:     ./_data
includes_dir: ./_app/_includes
#collections:  null

# PLUGINS
gems:
  - jekyll-seo-tag
  - jekyll-paginate
# - html-proofer
 #- jekyll-lunr-js-search
 #- jekyll-sitemap


paginate: 12
paginate_path: "/blog/page-:num/"
permalink: '/:categories/:path'
# FILES
include:
  - _landing_pages
exclude:
  - app
  - readme.md
  - todo.md
  - license.md
  - Gemfile
  - Gemfile.lock
  - bower.json
  - CNAME
  - node_modules
  - sass
  - gulpfile.js
  - package.json
  - javascript
  - vendor

# CONTENT
collections:
  backstory:
    output: false
  board:
    output: false
  mini-docs:
    output: true
  playlists:
    output: true
  staff_members:
    output: true
  posts:
    output: true
    permalink: '/:collection/:path/'
  reports:
    output: true
  related_coverage:
    output: true
  topics:
    output: true
  transcripts:
    output: true
    permalink: '/video/transcript/:path/'
  videos:
    output: true
    permalink: '/video/:path/'

# DEFAULTS
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
  - scope:
      path: ''
      type: 'backstory'
    values:
      layout: 'post'
  - scope:
      path: ''
      type: 'board'
    values:
      layout: 'post'
      no_page: true
  - scope:
      path: '_landing_pages'
      type: 'pages'
    values:
      layout: 'page'
      permalink: '/:basename/'
  - scope:
      path: ''
      type: 'playlists'
    values:
      layout: 'post'
  - scope:
      path: ''
      type: 'reports'
    values:
      layout: 'post'
  - scope:
      path: ''
      type: 'staff'
    values:
      layout: 'post'
  - scope:
      path: ''
      type: 'topics'
    values:
      layout: 'post'
  - scope:
      path: ''
      type: 'transcripts'
    values:
      layout: 'post'
  - scope:
      path: ''
      type: 'video'
    values:
      layout: 'post'
  - scope:
      path: ''
      type: 'voices'
    values:
      layout: 'page'